name: PR Build Check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    
permissions:
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

