name: PR Build Check

on:
  pull_request:
    types: [opened,synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - run: echo 'A review from octo-team was requested'
