name: PR Build Check

on:
  pull_request:
    types: [open, openend, synchronize]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: test
    - run: echo 'A review from octo-team was requested'
