name: PR Build Check

on:
  pull_request:
    types: [synchronize]

jobs:
  build:
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: echo 'A review from octo-team was requested'
